APPLICATION = gps-demo

BOARD ?= native

RIOTBASE ?= $(CURDIR)/../RIOT

FEATURES_REQUIRED += periph_uart periph_gpio

USEMODULE += xtimer

USEPKG += u8g2

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
